services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_boustify_dev
    environment:
      MYSQL_ROOT_PASSWORD: dVosYSOYmmMwKkNa
      MYSQL_DATABASE: boustify_dev
      MYSQL_USER: SlyCat_dev
      MYSQL_PASSWORD: nXVJU4QQdl9MPwRX
    ports:
      - "3306:3306"  # Port MySQL (hôte:conteneur)
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_boustify_dev
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8888:80"  # Accès à phpMyAdmin sur http://localhost:8888
    restart: unless-stopped

# Volumes pour persister les données MySQL
volumes:
  mysql_data:
    driver: local
